### ISSUE TITLE
setIPTracking, setUserAgentTracking, setURLTracking

### ISSUE THREAD

**Issue by cutesquirrel** [logmatic/logmatic-js#9]
Just to clarify, we don't have to replace the values in the method calls, it corresponds to the attribute names in the sent JSON.

Am I wrong ? Could you update the documentation please ?
thanks ;)

**Comment by Fenntasy** [comment]
You can if you wish but yeah, the string parameter is the key value name you will see in the logs.

I have changed these two parameters : 

```javascript
logmatic.setIPTracking("remote_addr")
logmatic.setUserAgentTracking("user_agent")
```

in order to be the same as the parameters gathered from nginx (and have only one custom parser for user_agent and geolocation).
If you let it as in the readme, you will have something like: 

```javascript
client: {
    IP: "192.168.1.1",
    user-agent: "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36"
}
```

So you can change them at will or let them like in the examples :)
